# -*- coding: utf-8 -*-
"""randomlunch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10b8gXSKHH41JuBA-T5pIGdqtyHv_SwmZ
"""

# app.py
import random
import os
import requests
import streamlit as st

# Streamlit 비밀값(Secrets) 또는 환경 변수에서 API 키 로드
KAKAO_REST_API_KEY = st.secrets.get("KAKAO_REST_API_KEY", os.getenv("KAKAO_REST_API_KEY", "YOUR_KEY_HERE"))

HEADERS = {
    "Authorization": f"KakaoAK {KAKAO_REST_API_KEY}"
}

FOOD_SEARCH_CATEGORIES = [
    "한식", "일식", "중식", "양식", "분식",
    "국밥", "찌개,전골", "칼국수", "냉면", "라멘",
    "돈까스", "초밥", "마라탕", "쌀국수",
    "버거", "피자", "파스타", "샐러드", "도시락"
]

EXCLUDE_CATEGORY_KEYWORDS = ["간이주점", "호프", "술집", "포장마차", "바(BAR)", "이자카야"]

def search_location_coords(keyword: str):
    url = "https://dapi.kakao.com/v2/local/search/keyword.json"
    params = {"query": keyword, "size": 1}
    try:
        res = requests.get(url, headers=HEADERS, params=params)
        res.raise_for_status()
        docs = res.json().get("documents", [])
        if not docs:
            return None
        target = docs[0]
        return {
            "place_name": target.get("place_name"),
            "address": target.get("road_address_name") or target.get("address_name"),
            "lat": float(target.get("y")),
            "lon": float(target.get("x"))
        }
    except Exception:
        return None

def fetch_all_restaurants(lat: float, lon: float, radius: int = 500):
    url = "https://dapi.kakao.com/v2/local/search/keyword.json"
    unique_restaurants = {}

    for category_keyword in FOOD_SEARCH_CATEGORIES:
        for page in range(1, 3):
            params = {
                "query": category_keyword,
                "category_group_code": "FD6",
                "x": str(lon),
                "y": str(lat),
                "radius": radius,
                "page": page,
                "size": 15,
                "sort": "distance"
            }
            try:
                res = requests.get(url, headers=HEADERS, params=params)
                res.raise_for_status()
                data = res.json()
                for doc in data.get("documents", []):
                    cat_name = doc.get("category_name", "")
                    if any(ex in cat_name for ex in EXCLUDE_CATEGORY_KEYWORDS):
                        continue
                    doc_id = doc.get("id")
                    if doc_id not in unique_restaurants:
                        unique_restaurants[doc_id] = doc
                if data.get("meta", {}).get("is_end", True):
                    break
            except Exception:
                break

    return list(unique_restaurants.values())

# --- 웹 화면 구성 ---
st.set_page_config(page_title="오늘 뭐 먹지?", page_icon="🍚")

st.title("🍚 오늘 뭐 먹지? 식당 랜덤깡")
st.caption("카카오맵 데이터를 기반으로 반경 내 식사 가능한 음식점을 무작위 추천합니다.")

location_input = st.text_input("기준 위치 (예: 고려대학교 SK미래관, 안암역, 안암로 145)", value="고려대학교 SK미래관")
radius_choice = st.radio("검색 반경", options=[300, 500, 1000], format_func=lambda x: f"{x}m", horizontal=True, index=1)

if st.button("🎲 식당 추천받기", type="primary"):
    if not location_input:
        st.warning("위치를 입력해주세요.")
    else:
        with st.spinner("주변 식당을 탐색하고 있습니다..."):
            loc = search_location_coords(location_input)
            if not loc:
                st.error("입력한 위치를 찾을 수 없습니다. 정확한 명칭이나 주소를 입력해주세요.")
            else:
                st.info(f"📍 기준점: **{loc['place_name']}** ({loc['address']})")
                restaurants = fetch_all_restaurants(loc["lat"], loc["lon"], radius=radius_choice)

                if not restaurants:
                    st.warning("반경 내에 식사 가능한 음식점을 찾을 수 없습니다.")
                else:
                    selected = random.choice(restaurants)
                    category_clean = selected.get("category_name", "").replace("음식점 > ", "")

                    st.success(f"총 {len(restaurants)}곳 중 1곳을 선정했습니다!")
                    st.subheader(f"🍴 {selected.get('place_name')}")
                    st.write(f"- **분류:** {category_clean}")
                    st.write(f"- **거리:** 약 {selected.get('distance')}m")
                    st.write(f"- **주소:** {selected.get('road_address_name') or selected.get('address_name')}")
                    st.write(f"- **전화번호:** {selected.get('phone') or '등록 정보 없음'}")
                    st.link_button("카카오맵에서 보기", selected.get("place_url"))
